# Generated by Django 2.2.6 on 2020-02-04 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerSiteAllowedField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomerSiteAllowedFields', related_query_name='CustomerSiteAllowedFields', to='accounting.ConsumerSite')),
            ],
            options={
                'unique_together': {('site', 'field_name')},
            },
        ),
    ]
