# Generated by Django 2.2.6 on 2020-02-04 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=50)),
                ('private_key', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PendingAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, region=None)),
                ('verification_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=20, null=True, verbose_name='نام')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=70, null=True, unique=True, verbose_name='پست الکترونیکی')),
                ('address', models.TextField(max_length=500, null=True, verbose_name='آدرس منزل')),
                ('gender', models.CharField(max_length=5, null=True, verbose_name='جنسیت')),
                ('bio', models.TextField(max_length=500, null=True, verbose_name='زندگی نامه')),
                ('born', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد به میلادی')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='قد بر حسب سانتی متر')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='وزن برحسب کیلوگرم')),
                ('national', models.CharField(max_length=20, null=True, verbose_name='ملیت')),
                ('phone_verified', models.BooleanField(default=False, verbose_name=' تلفن شما تایید شده است')),
                ('image', models.ImageField(blank=True, upload_to='user_photos', verbose_name='تصویر شما')),
                ('using_sites', models.ManyToManyField(blank=True, related_name='users', related_query_name='users', to='accounting.ConsumerSite', verbose_name='سایت های مورد استفاده')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicField',
            fields=[
                ('field_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('field_type', models.CharField(choices=[('DesiredCharField', 'DesiredCharField'), ('DesiredTextField', 'DesiredTextField'), ('DesiredIntegerField', 'DesiredIntegerField'), ('DesiredBooleanField', 'DesiredBooleanField'), ('DesiredImageField', 'DesiredImageField'), ('DesiredEmailField', 'DesiredEmailField')], max_length=50)),
                ('explanation', models.TextField(max_length=500, null=True)),
            ],
            options={
                'unique_together': {('field_name', 'field_type')},
            },
        ),
        migrations.AddField(
            model_name='consumersite',
            name='owners',
            field=models.ManyToManyField(related_name='providingSites', related_query_name='providingSites', to='accounting.Profile'),
        ),
        migrations.CreateModel(
            name='DesiredTextField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.TextField(max_length=500, null=True)),
                ('field_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.DynamicField')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DesiredTextFields', related_query_name='DesiredTextFields', to='accounting.Profile')),
            ],
            options={
                'unique_together': {('profile', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='DesiredIntegerField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.BigIntegerField(default=0)),
                ('field_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.DynamicField')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DesiredBigIntFields', related_query_name='DesiredBigIntFields', to='accounting.Profile')),
            ],
            options={
                'unique_together': {('profile', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='DesiredImageField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.ImageField(null=True, upload_to='assets/profiles')),
                ('field_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.DynamicField')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DesiredImageFields', related_query_name='DesiredImageFields', to='accounting.Profile')),
            ],
            options={
                'unique_together': {('profile', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='DesiredEmailField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.EmailField(max_length=70)),
                ('field_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.DynamicField')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DesiredEmailFields', related_query_name='DesiredEmailFields', to='accounting.Profile')),
            ],
            options={
                'unique_together': {('profile', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='DesiredCharField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=50)),
                ('field_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.DynamicField')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DesiredCharFields', related_query_name='DesiredCharFields', to='accounting.Profile')),
            ],
            options={
                'unique_together': {('profile', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='DesiredBooleanField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.BooleanField()),
                ('field_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.DynamicField')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DesiredBools', related_query_name='DesiredBools', to='accounting.Profile')),
            ],
            options={
                'unique_together': {('profile', 'field_name')},
            },
        ),
    ]
